apiVersion: v1 
kind: Secret
metadata: 
  name: git-basic-creds
  namespace: eazytraining
  annotations: 
    tekton.dev/git-0: ${GITLAB_HOST_FQDN}
type: kubernetes.io/basic-auth
stringData:
  username: ${GIT_USERNAME}
  password: ${GIT_PASSWORD}
  